CREATE TABLE IF NOT EXISTS custom_quote_requests (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  request_code VARCHAR(40) NOT NULL UNIQUE,
  user_id INT UNSIGNED NULL,
  customer_name VARCHAR(160) NOT NULL,
  phone VARCHAR(40) NOT NULL,
  email VARCHAR(180) NULL,
  product_name VARCHAR(180) NOT NULL,
  size_dimension VARCHAR(160) NULL,
  material_type VARCHAR(160) NULL,
  quantity VARCHAR(80) NULL,
  instructions TEXT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'new',
  admin_notes TEXT NULL,
  quoted_amount DECIMAL(12,2) NULL,
  currency VARCHAR(10) NOT NULL DEFAULT 'INR',
  source_page VARCHAR(255) NULL,
  ip_address VARCHAR(64) NULL,
  user_agent VARCHAR(255) NULL,
  order_id INT UNSIGNED NULL,
  approved_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_custom_quote_status (status, created_at),
  KEY idx_custom_quote_phone (phone),
  KEY idx_custom_quote_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
