<?php
$dealEditId = (int)($dealEditId ?? 0);
$pageTitle = $dealEditId > 0 ? 'Edit Deal — RCS Admin' : 'Add Deal — RCS Admin';
$currentAdmPage = 'deals';
include __DIR__ . '/layout.php';
?>
<div class="adm-pt"><?= $dealEditId > 0 ? 'Edit Deal' : 'Add Deal' ?></div>
<div class="fsec" style="max-width:980px">
  <div style="display:flex;justify-content:space-between;gap:10px;flex-wrap:wrap;align-items:center;margin-bottom:14px">
    <div style="font-size:13px;color:var(--text2)">Create or update homepage deal cards from this dedicated page.</div>
    <a class="btn btn-outline btn-sm" href="/admin/deals">← Back to Deals</a>
  </div>
  <div id="dealErr" style="display:none;padding:10px 12px;border:1px solid var(--red-mid);background:var(--red-bg);color:var(--red);border-radius:10px;font-size:12px;margin-bottom:10px"></div>
  <div style="font-weight:700;margin-bottom:10px" id="dealFormTitle"><?= $dealEditId > 0 ? 'Edit Deal' : 'Add Deal' ?></div>
  <div class="f2"><div class="fg"><label>Card Type</label><select class="fi fi-sel" id="deal-type" onchange="toggleDealHelp()"><option value="deal">Normal Deal Card</option><option value="promo">Promo / Offer Card</option></select></div><div class="fg"><label>Color Theme</label><select class="fi fi-sel" id="deal-theme"><option value="green">Green</option><option value="orange">Orange</option><option value="purple">Purple</option></select></div></div>
  <div class="f2"><div class="fg"><label>Title *</label><input class="fi" id="deal-title" placeholder="500 Visiting Cards"></div><div class="fg"><label>Highlight Text</label><input class="fi" id="deal-highlight" placeholder="FREE Design"></div></div>
  <div class="f2"><div class="fg"><label>Subtitle</label><input class="fi" id="deal-subtitle" placeholder="Starting from"></div><div class="fg"><label>Price Text <span style="color:var(--text3);font-weight:500">(required for normal deal)</span></label><input class="fi" id="deal-price" placeholder="₹199"></div></div>
  <div class="fg"><label>Description <span style="color:var(--text3);font-weight:500">(optional)</span></label><textarea class="fi" id="deal-description" style="height:64px"></textarea></div>
  <div class="f2"><div class="fg"><label>Deal Image</label><input type="file" class="fi" id="deal-image" accept=".jpg,.jpeg,.png,.webp,image/jpeg,image/png,image/webp" onchange="uploadDealImage()"><div id="dealHelp" style="font-size:11px;color:var(--text3);margin-top:5px">Normal deal cards require an image. Choose image — upload starts automatically.</div></div><div class="fg"><label>Image Path</label><input class="fi" id="deal-image-path" placeholder="/uploads/deals/..."></div></div>
  <div class="f2"><div class="fg"><label>Image Alt</label><input class="fi" id="deal-alt" placeholder="500 visiting cards printing deal"></div><div class="fg"><label>Sort Order</label><input type="number" class="fi" id="deal-sort" value="0"></div></div>
  <div class="f2"><div class="fg"><label>CTA Text</label><input class="fi" id="deal-cta-text" placeholder="Order Now"></div><div class="fg"><label>CTA URL</label><input class="fi" id="deal-cta-url" placeholder="/categories"></div></div>
  <div class="fg"><label>Status</label><select class="fi fi-sel" id="deal-active"><option value="1">Active</option><option value="0">Inactive</option></select></div>
  <div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:12px"><span id="dealUploadState" style="align-self:center;font-size:11px;color:var(--text3);font-weight:800">Deal image uploads immediately after selection.</span><button class="btn btn-blue btn-sm" onclick="saveDeal()" id="dealSaveBtn"><?= $dealEditId > 0 ? 'Update Deal' : 'Save Deal' ?></button><a class="btn btn-outline btn-sm" href="/admin/deals">Cancel</a></div>
</div>
<script>
const DEAL_EDIT_ID = <?= (int)$dealEditId ?>;
const CSRF = '<?= htmlspecialchars($csrf??'') ?>';
let editId = DEAL_EDIT_ID;
function showErr(msg=''){ const e=document.getElementById('dealErr'); if(!e) return; if(!msg){e.style.display='none';return;} e.textContent=msg; e.style.display='block'; }
function toastMsg(msg,type='info'){ const w=document.getElementById('tw'); const t=document.createElement('div'); t.className='toast '+type; t.textContent=msg; w.appendChild(t); requestAnimationFrame(()=>requestAnimationFrame(()=>t.classList.add('show'))); setTimeout(()=>{t.classList.remove('show'); setTimeout(()=>t.remove(),300);},2600); }
function toggleDealHelp(){ const type = document.getElementById('deal-type').value; document.getElementById('dealHelp').textContent = type === 'promo' ? 'Promo cards can use default gift art. Choose image only if you want to replace it.' : 'Normal deal cards require an image. Choose image — upload starts automatically.'; }
function fillForm(d){ editId = Number(d.id || DEAL_EDIT_ID || 0); document.getElementById('dealFormTitle').textContent = editId ? `Edit Deal #${editId}` : 'Add Deal'; document.getElementById('deal-type').value=d.deal_type||'deal'; document.getElementById('deal-theme').value=d.color_theme||'green'; document.getElementById('deal-title').value=d.title||''; document.getElementById('deal-highlight').value=d.highlight_text||''; document.getElementById('deal-subtitle').value=d.subtitle||''; document.getElementById('deal-price').value=d.price_text||''; document.getElementById('deal-description').value=d.description||''; document.getElementById('deal-image-path').value=d.image_path||''; document.getElementById('deal-alt').value=d.image_alt||''; document.getElementById('deal-cta-text').value=d.cta_text||''; document.getElementById('deal-cta-url').value=d.cta_url||''; document.getElementById('deal-sort').value=Number(d.sort_order||0); document.getElementById('deal-active').value=Number(d.is_active??1)?'1':'0'; const state=document.getElementById('dealUploadState'); if(state){state.textContent='Deal image uploads immediately after selection.';state.style.color='var(--text3)';} toggleDealHelp(); }
function collectForm(){ return {deal_type:document.getElementById('deal-type').value,color_theme:document.getElementById('deal-theme').value,title:document.getElementById('deal-title').value.trim(),highlight_text:document.getElementById('deal-highlight').value.trim(),subtitle:document.getElementById('deal-subtitle').value.trim(),price_text:document.getElementById('deal-price').value.trim(),description:document.getElementById('deal-description').value.trim(),image_path:document.getElementById('deal-image-path').value.trim(),image_alt:document.getElementById('deal-alt').value.trim(),cta_text:document.getElementById('deal-cta-text').value.trim(),cta_url:document.getElementById('deal-cta-url').value.trim(),sort_order:parseInt(document.getElementById('deal-sort').value||'0',10)||0,is_active:parseInt(document.getElementById('deal-active').value||'1',10)||0}; }
async function loadForEdit(){ if(!DEAL_EDIT_ID){ fillForm({deal_type:'deal',color_theme:'green',subtitle:'Starting from',cta_text:'Order Now',cta_url:'/categories',is_active:1}); return; } const res=await fetch('/admin/api/deals').then(r=>r.json()); const d=(res.deals||[]).find(x=>Number(x.id)===DEAL_EDIT_ID); if(!d){ showErr('Deal not found'); return; } fillForm(d); }
async function saveDeal(){ const payload=collectForm(); if(!payload.title){showErr('Deal title is required.');return;} if(payload.deal_type==='deal'&&!payload.image_path){showErr('Normal deal image is required.');return;} if(payload.deal_type==='deal'&&!payload.price_text){showErr('Normal deal price is required.');return;} const btn=document.getElementById('dealSaveBtn'); btn.disabled=true; btn.textContent='Saving...'; try{ const url=editId?`/admin/api/deals/${editId}`:'/admin/api/deals'; const method=editId?'PUT':'POST'; const res=await fetch(url,{method,headers:{'Content-Type':'application/json','X-CSRF-TOKEN':CSRF},body:JSON.stringify(payload)}).then(r=>r.json()); if(!res.ok){showErr(res.msg||'Save failed');return;} toastMsg(editId?'Deal updated':'Deal created','success'); window.location.href='/admin/deals'; } finally{ btn.disabled=false; btn.textContent=DEAL_EDIT_ID?'Update Deal':'Save Deal'; } }
async function uploadDealImage(){ const input=document.getElementById('deal-image'); const state=document.getElementById('dealUploadState'); const file=input?.files?.[0]; if(!file){showErr('Select image first.');return;} if(input) input.disabled=true; if(state){state.textContent='Uploading deal image…';state.style.color='var(--blue)';} const fd=new FormData(); fd.append('image',file); try{ const res=await fetch('/admin/api/deals/upload',{method:'POST',headers:{'X-CSRF-TOKEN':CSRF},body:fd}).then(r=>r.json()); if(!res.ok){showErr(res.msg||'Upload failed'); if(state){state.textContent='Upload failed. Choose image again.';state.style.color='var(--red)';} return;} document.getElementById('deal-image-path').value=res.path||''; showErr(''); if(state){state.textContent='Deal image uploaded automatically.';state.style.color='var(--green)';} toastMsg('Image uploaded','success'); } finally { if(input) input.disabled=false; } }
loadForEdit();
</script>
    </div></div></div>
</body></html>
